#!/usr/bin/env bash
# UnityEnv: Share Nix environment variables with Arch login shells

set -euo pipefail

usage() {
  cat <<USAGE
Usage: $(basename "$0") update [USER]

Update /etc/profile.d/nixarch-env.sh with variables from the given USER's
home-manager environment (defaults to 'lars').
USAGE
}

update_env() {
  local user="$1"
  local src="/home/${user}/.nix-profile/etc/profile.d/hm-session-vars.sh"
  local dst="/etc/profile.d/nixarch-env.sh"

  if [[ ! -f "$src" ]]; then
    echo "[UnityEnv] Source $src not found" >&2
    return 1
  fi

  echo "[UnityEnv] Writing $dst" >&2
  {
    echo "# Generated by UnityEnv from $src";
    grep '^export ' "$src" | sed 's/^export //';
  } > "$dst"
}

case "${1:-}" in
  update)
    update_env "${2:-lars}"
    ;;
  *)
    usage
    ;;
esac
